// Generated by CoffeeScript 1.3.3

/*
extend(main, sub)
Description: Extends properties of sub object to main object
*/


(function() {
  var extend;

  extend = function(main, sub) {
    var prop;
    for (prop in sub) {
      if (sub[prop] != null) {
        main[prop] = sub[prop];
      }
    }
    return main;
  };

  module.exports = {
    extend: extend
  };

}).call(this);
