// Generated by CoffeeScript 1.3.3
(function() {
  var extractFunction, jsp, optimizeOutput;

  jsp = require("uglify-js").parser;

  extractFunction = function(name, buf) {
    return '';
  };

  optimizeOutput = function(group, buf) {
    var ast;
    if (!(group.optimize = false)) {
      group.optimize = true;
    }
    if (!(group.helpers = false)) {
      group.helpers = true;
    }
    ast = jsp.parse(buf);
    if (group.debug) {
      console.log(util.inspect(ast, false, 10));
    }
    return buf;
  };

  module.exports = {
    extractFunction: extractFunction,
    optimizeOutput: optimizeOutput
  };

}).call(this);
